apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "teleplug"
  description: "Teleplug is a dead simple opentelemetry-instrumented plug"
spec:
  type: "library"
  lifecycle: production
  owner: "group:default/team-developer-experience"
  system: prima.it
